import { Stock } from './types';

export const STOCKS: Stock[] = [
  // Communication Services
  { ticker: 'GOOGL', name: 'Alphabet Inc (Class A)',          price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'GOOG',  name: 'Alphabet Inc (Class C)',          price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'T',     name: 'AT&T Inc',                        price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'CHTR',  name: 'Charter Communications',          price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'CMCSA', name: 'Comcast Corp',                    price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'EA',    name: 'Electronic Arts',                 price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'FOXA',  name: 'Fox Corporation (Class A)',       price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'FOX',   name: 'Fox Corporation (Class B)',       price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'LYV',   name: 'Live Nation Entertainment',       price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'META',  name: 'Meta Platforms Inc',              price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'NFLX',  name: 'Netflix Inc',                     price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'NWSA',  name: 'News Corp (Class A)',             price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'NWS',   name: 'News Corp (Class B)',             price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'OMC',   name: 'Omnicom Group',                   price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'TMUS',  name: 'T-Mobile US',                     price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'TTWO',  name: 'Take-Two Interactive',            price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'TKO',   name: 'TKO Group Holdings',              price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'TTD',   name: 'Trade Desk Inc',                  price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'VZ',    name: 'Verizon Communications',          price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'WBD',   name: 'Warner Bros. Discovery',          price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'DIS',   name: 'Walt Disney Co',                  price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  // Consumer Discretionary
  { ticker: 'ABNB',  name: 'Airbnb Inc',                      price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'AMZN',  name: 'Amazon.com Inc',                  price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'APTV',  name: 'Aptiv PLC',                       price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'AZO',   name: 'AutoZone Inc',                    price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'BBY',   name: 'Best Buy Co',                     price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'BKNG',  name: 'Booking Holdings',                price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'CCL',   name: 'Carnival Corp',                   price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'CVNA',  name: 'Carvana Co',                      price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'CMG',   name: 'Chipotle Mexican Grill',          price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'DRI',   name: 'Darden Restaurants',              price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'DECK',  name: 'Deckers Brands',                  price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'DASH',  name: 'DoorDash Inc',                    price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'DHI',   name: 'D.R. Horton Inc',                 price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'EBAY',  name: 'eBay Inc',                        price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'EXPE',  name: 'Expedia Group',                   price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'F',     name: 'Ford Motor Co',                   price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'GRMN',  name: 'Garmin Ltd',                      price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'GM',    name: 'General Motors Co',               price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'GPC',   name: 'Genuine Parts Co',                price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'HAS',   name: 'Hasbro Inc',                      price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'HLT',   name: 'Hilton Worldwide',                price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'HD',    name: 'Home Depot Inc',                  price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'LVS',   name: 'Las Vegas Sands',                 price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'LEN',   name: 'Lennar Corp',                     price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'LOW',   name: "Lowe's Companies",                price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'LULU',  name: 'Lululemon Athletica',             price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'MAR',   name: 'Marriott International',          price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'MCD',   name: "McDonald's Corp",                 price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'MGM',   name: 'MGM Resorts International',       price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'NKE',   name: 'Nike Inc',                        price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'NCLH',  name: 'Norwegian Cruise Line',           price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'NVR',   name: 'NVR Inc',                         price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'ORLY',  name: "O'Reilly Automotive",             price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'POOL',  name: 'Pool Corporation',                price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'PHM',   name: 'PulteGroup Inc',                  price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'RL',    name: 'Ralph Lauren Corp',               price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'RCL',   name: 'Royal Caribbean Group',           price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'ROST',  name: 'Ross Stores Inc',                 price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'SBUX',  name: 'Starbucks Corp',                  price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'TPR',   name: 'Tapestry Inc',                    price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'TGT',   name: 'Target Corp',                     price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'TSLA',  name: 'Tesla Inc',                       price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'TJX',   name: 'TJX Companies',                   price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'TSCO',  name: 'Tractor Supply Co',               price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'ULTA',  name: 'Ulta Beauty Inc',                 price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'WSM',   name: 'Williams-Sonoma Inc',             price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'WYNN',  name: 'Wynn Resorts',                    price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'YUM',   name: 'Yum! Brands Inc',                 price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  // Consumer Staples
  { ticker: 'MO',    name: 'Altria Group Inc',                price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'ADM',   name: 'Archer Daniels Midland',          price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'CPB',   name: "Campbell's Company",              price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'CHD',   name: 'Church & Dwight',                 price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'CLX',   name: 'Clorox Co',                       price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'KO',    name: 'Coca-Cola Co',                    price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'CL',    name: 'Colgate-Palmolive',               price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'CAG',   name: 'Conagra Brands',                  price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'STZ',   name: 'Constellation Brands',            price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'COST',  name: 'Costco Wholesale',                price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'DG',    name: 'Dollar General Corp',             price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'DLTR',  name: 'Dollar Tree Inc',                 price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'EL',    name: 'Estée Lauder Companies',          price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'GIS',   name: 'General Mills Inc',               price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'HSY',   name: 'Hershey Co',                      price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'HRL',   name: 'Hormel Foods',                    price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'KVUE',  name: 'Kenvue Inc',                      price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'KDP',   name: 'Keurig Dr Pepper',                price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'KMB',   name: 'Kimberly-Clark',                  price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'KHC',   name: 'Kraft Heinz Co',                  price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'KR',    name: 'Kroger Co',                       price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'MKC',   name: 'McCormick & Company',             price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'MDLZ',  name: 'Mondelez International',          price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'MNST',  name: 'Monster Beverage',                price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'PEP',   name: 'PepsiCo Inc',                     price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'PM',    name: 'Philip Morris International',     price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'PG',    name: 'Procter & Gamble',                price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'SJM',   name: 'J.M. Smucker Co',                 price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'SYY',   name: 'Sysco Corp',                      price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'TSN',   name: 'Tyson Foods',                     price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'WMT',   name: 'Walmart Inc',                     price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  // Energy
  { ticker: 'APA',   name: 'APA Corporation',                 price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'BKR',   name: 'Baker Hughes Co',                 price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'CVX',   name: 'Chevron Corp',                    price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'COP',   name: 'ConocoPhillips',                  price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'CTRA',  name: 'Coterra Energy',                  price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'DVN',   name: 'Devon Energy',                    price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'FANG',  name: 'Diamondback Energy',              price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'EOG',   name: 'EOG Resources',                   price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'EQT',   name: 'EQT Corporation',                 price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'XOM',   name: 'ExxonMobil Corp',                 price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'HAL',   name: 'Halliburton Co',                  price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'KMI',   name: 'Kinder Morgan Inc',               price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'MPC',   name: 'Marathon Petroleum',              price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'OXY',   name: 'Occidental Petroleum',            price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'OKE',   name: 'Oneok Inc',                       price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'PSX',   name: 'Phillips 66',                     price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'SLB',   name: 'SLB (Schlumberger)',              price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'TRGP',  name: 'Targa Resources',                 price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'TPL',   name: 'Texas Pacific Land Corp',         price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'VLO',   name: 'Valero Energy',                   price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'WMB',   name: 'Williams Companies',              price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  // Financials
  { ticker: 'AFL',   name: 'Aflac Inc',                       price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'ALL',   name: 'Allstate Corp',                   price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'AXP',   name: 'American Express Co',             price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'AIG',   name: 'American International Group',    price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'AMP',   name: 'Ameriprise Financial',            price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'AON',   name: 'Aon PLC',                         price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'APO',   name: 'Apollo Global Management',        price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'ACGL',  name: 'Arch Capital Group',              price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'ARES',  name: 'Ares Management',                 price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'AJG',   name: 'Arthur J. Gallagher & Co',        price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'AIZ',   name: 'Assurant Inc',                    price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'BAC',   name: 'Bank of America Corp',            price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'BRK-B', name: 'Berkshire Hathaway B',            price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'BLK',   name: 'BlackRock Inc',                   price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'BX',    name: 'Blackstone Inc',                  price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'BK',    name: 'BNY Mellon',                      price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'COF',   name: 'Capital One Financial',           price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'CBOE',  name: 'Cboe Global Markets',             price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'SCHW',  name: 'Charles Schwab Corp',             price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'CB',    name: 'Chubb Limited',                   price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'CINF',  name: 'Cincinnati Financial',            price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'C',     name: 'Citigroup Inc',                   price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'CFG',   name: 'Citizens Financial Group',        price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'CME',   name: 'CME Group Inc',                   price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'COIN',  name: 'Coinbase Global',                 price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'CPAY',  name: 'Corpay Inc',                      price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'EG',    name: 'Everest Group',                   price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'ERIE',  name: 'Erie Indemnity Co',               price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'FDS',   name: 'FactSet Research Systems',        price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'FIS',   name: 'Fidelity National Information',   price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'FITB',  name: 'Fifth Third Bancorp',             price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'FISV',  name: 'Fiserv Inc',                      price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'BEN',   name: 'Franklin Resources',              price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'GL',    name: 'Globe Life Inc',                  price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'GPN',   name: 'Global Payments Inc',             price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'GS',    name: 'Goldman Sachs Group',             price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'HIG',   name: 'Hartford Financial Services',     price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'HOOD',  name: 'Robinhood Markets',               price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'HBAN',  name: 'Huntington Bancshares',           price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'IBKR',  name: 'Interactive Brokers',             price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'ICE',   name: 'Intercontinental Exchange',       price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'IVZ',   name: 'Invesco Ltd',                     price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'JKHY',  name: 'Jack Henry & Associates',         price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'JPM',   name: 'JPMorgan Chase & Co',             price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'KEY',   name: 'KeyCorp',                         price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'KKR',   name: 'KKR & Co Inc',                    price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'L',     name: 'Loews Corporation',               price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'MA',    name: 'Mastercard Inc',                  price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'MTB',   name: 'M&T Bank Corp',                   price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'MMC',   name: 'Marsh McLennan',                  price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'MET',   name: 'MetLife Inc',                     price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'MCO',   name: "Moody's Corporation",             price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'MS',    name: 'Morgan Stanley',                  price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'MSCI',  name: 'MSCI Inc',                        price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'NDAQ',  name: 'Nasdaq Inc',                      price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'NTRS',  name: 'Northern Trust Corp',             price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'PNC',   name: 'PNC Financial Services',          price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'PFG',   name: 'Principal Financial Group',       price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'PGR',   name: 'Progressive Corp',                price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'PRU',   name: 'Prudential Financial',            price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'PYPL',  name: 'PayPal Holdings',                 price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'RJF',   name: 'Raymond James Financial',         price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'RF',    name: 'Regions Financial Corp',          price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'SPGI',  name: 'S&P Global Inc',                  price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'STT',   name: 'State Street Corp',               price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'SYF',   name: 'Synchrony Financial',             price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'TROW',  name: 'T. Rowe Price Group',             price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'TRV',   name: 'Travelers Companies',             price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'TFC',   name: 'Truist Financial',                price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'USB',   name: 'U.S. Bancorp',                    price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'V',     name: 'Visa Inc',                        price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'WRB',   name: 'W. R. Berkley Corp',              price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'WFC',   name: 'Wells Fargo & Co',                price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'WTW',   name: 'Willis Towers Watson',            price: 0, chg: 0, sector: 'Financials',             vol: '' },
  // Health Care
  { ticker: 'ABT',   name: 'Abbott Laboratories',             price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'ABBV',  name: 'AbbVie Inc',                      price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'A',     name: 'Agilent Technologies',            price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'ALGN',  name: 'Align Technology',                price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'AMGN',  name: 'Amgen Inc',                       price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'BAX',   name: 'Baxter International',            price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'BDX',   name: 'Becton Dickinson',                price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'BIIB',  name: 'Biogen Inc',                      price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'BSX',   name: 'Boston Scientific',               price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'BMY',   name: 'Bristol Myers Squibb',            price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'CAH',   name: 'Cardinal Health',                 price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'COR',   name: 'Cencora Inc',                     price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'CNC',   name: 'Centene Corporation',             price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'CRL',   name: 'Charles River Laboratories',      price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'CI',    name: 'Cigna Group',                     price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'COO',   name: 'Cooper Companies',                price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'CVS',   name: 'CVS Health Corp',                 price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'DHR',   name: 'Danaher Corporation',             price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'DVA',   name: 'DaVita Inc',                      price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'DXCM',  name: 'Dexcom Inc',                      price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'EW',    name: 'Edwards Lifesciences',            price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'ELV',   name: 'Elevance Health',                 price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'GEHC',  name: 'GE HealthCare Technologies',      price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'GILD',  name: 'Gilead Sciences',                 price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'HCA',   name: 'HCA Healthcare',                  price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'HSIC',  name: 'Henry Schein Inc',                price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'HOLX',  name: 'Hologic Inc',                     price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'HUM',   name: 'Humana Inc',                      price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'IDXX',  name: 'Idexx Laboratories',              price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'INCY',  name: 'Incyte Corporation',              price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'PODD',  name: 'Insulet Corporation',             price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'ISRG',  name: 'Intuitive Surgical',              price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'IQV',   name: 'IQVIA Holdings',                  price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'JNJ',   name: 'Johnson & Johnson',               price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'LH',    name: 'Labcorp',                         price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'LLY',   name: 'Eli Lilly and Co',                price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'MCK',   name: 'McKesson Corporation',            price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'MDT',   name: 'Medtronic PLC',                   price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'MRK',   name: 'Merck & Co',                      price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'MTD',   name: 'Mettler-Toledo International',    price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'MRNA',  name: 'Moderna Inc',                     price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'NVO',   name: 'Novo Nordisk A/S',                price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'PFE',   name: 'Pfizer Inc',                      price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'DGX',   name: 'Quest Diagnostics',               price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'REGN',  name: 'Regeneron Pharmaceuticals',       price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'RMD',   name: 'ResMed Inc',                      price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'STE',   name: 'Steris PLC',                      price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'SYK',   name: 'Stryker Corporation',             price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'TMO',   name: 'Thermo Fisher Scientific',        price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'UNH',   name: 'UnitedHealth Group',              price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'UHS',   name: 'Universal Health Services',       price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'VRTX',  name: 'Vertex Pharmaceuticals',          price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'VTRS',  name: 'Viatris Inc',                     price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'WAT',   name: 'Waters Corporation',              price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'ZBH',   name: 'Zimmer Biomet Holdings',          price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'ZTS',   name: 'Zoetis Inc',                      price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  // Industrials
  { ticker: 'MMM',   name: '3M Co',                           price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'AOS',   name: 'A. O. Smith Corp',                price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'ALLE',  name: 'Allegion PLC',                    price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'AME',   name: 'Ametek Inc',                      price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'ADP',   name: 'Automatic Data Processing',       price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'AXON',  name: 'Axon Enterprise Inc',             price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'BA',    name: 'Boeing Co',                       price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'BLDR',  name: 'Builders FirstSource',            price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'BR',    name: 'Broadridge Financial Solutions',  price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'CARR',  name: 'Carrier Global Corp',             price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'CAT',   name: 'Caterpillar Inc',                 price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'CHRW',  name: 'C.H. Robinson Worldwide',         price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'CTAS',  name: 'Cintas Corporation',              price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'CPRT',  name: 'Copart Inc',                      price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'CSX',   name: 'CSX Corporation',                 price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'CMI',   name: 'Cummins Inc',                     price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'DAL',   name: 'Delta Air Lines',                 price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'DE',    name: 'Deere & Company',                 price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'DOV',   name: 'Dover Corporation',               price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'ETN',   name: 'Eaton Corporation',               price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'EME',   name: 'Emcor Group',                     price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'EMR',   name: 'Emerson Electric',                price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'EFX',   name: 'Equifax Inc',                     price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'EXPD',  name: 'Expeditors International',        price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'FAST',  name: 'Fastenal Co',                     price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'FDX',   name: 'FedEx Corp',                      price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'FTV',   name: 'Fortive Corp',                    price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'GE',    name: 'GE Aerospace',                    price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'GEV',   name: 'GE Vernova',                      price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'GNRC',  name: 'Generac Holdings',                price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'GD',    name: 'General Dynamics',                price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'HON',   name: 'Honeywell International',         price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'HWM',   name: 'Howmet Aerospace',                price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'HUBB',  name: 'Hubbell Incorporated',            price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'HII',   name: 'Huntington Ingalls Industries',   price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'IEX',   name: 'IDEX Corporation',                price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'ITW',   name: 'Illinois Tool Works',             price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'IR',    name: 'Ingersoll Rand Inc',              price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'JBHT',  name: 'J.B. Hunt Transport Services',    price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'J',     name: 'Jacobs Solutions Inc',            price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'JCI',   name: 'Johnson Controls International',  price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'LHX',   name: 'L3Harris Technologies',           price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'LDOS',  name: 'Leidos Holdings',                 price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'LII',   name: 'Lennox International',            price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'LMT',   name: 'Lockheed Martin Corp',            price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'MAS',   name: 'Masco Corporation',               price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'MLM',   name: 'Martin Marietta Materials',       price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'NDSN',  name: 'Nordson Corporation',             price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'NSC',   name: 'Norfolk Southern Corp',           price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'NOC',   name: 'Northrop Grumman',                price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'ODFL',  name: 'Old Dominion Freight Line',       price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'OTIS',  name: 'Otis Worldwide Corp',             price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'PCAR',  name: 'Paccar Inc',                      price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'PH',    name: 'Parker Hannifin Corp',            price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'PAYX',  name: 'Paychex Inc',                     price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'PNR',   name: 'Pentair PLC',                     price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'PWR',   name: 'Quanta Services',                 price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'RSG',   name: 'Republic Services Inc',           price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'ROK',   name: 'Rockwell Automation',             price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'ROL',   name: 'Rollins Inc',                     price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'ROP',   name: 'Roper Technologies',              price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'RTX',   name: 'RTX Corp',                        price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'SNA',   name: 'Snap-on Incorporated',            price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'LUV',   name: 'Southwest Airlines',              price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'SWK',   name: 'Stanley Black & Decker',          price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'TXT',   name: 'Textron Inc',                     price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'TT',    name: 'Trane Technologies',              price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'TDG',   name: 'TransDigm Group',                 price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'TRMB',  name: 'Trimble Inc',                     price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'TYL',   name: 'Tyler Technologies',              price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'UBER',  name: 'Uber Technologies',               price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'UAL',   name: 'United Airlines Holdings',        price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'UPS',   name: 'United Parcel Service',           price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'URI',   name: 'United Rentals Inc',              price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'UNP',   name: 'Union Pacific Corp',              price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'VLTO',  name: 'Veralto Corp',                    price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'VRSK',  name: 'Verisk Analytics',                price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'VRT',   name: 'Vertiv Holdings',                 price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'WAB',   name: 'Wabtec Corporation',              price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'WM',    name: 'Waste Management Inc',            price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'GWW',   name: 'W. W. Grainger Inc',              price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'XYL',   name: 'Xylem Inc',                       price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  // Technology
  { ticker: 'ACN',   name: 'Accenture PLC',                   price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'ADBE',  name: 'Adobe Inc',                       price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'AMD',   name: 'Advanced Micro Devices',          price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'AKAM',  name: 'Akamai Technologies',             price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'APH',   name: 'Amphenol Corporation',            price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'ADI',   name: 'Analog Devices Inc',              price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'ANET',  name: 'Arista Networks',                 price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'ADSK',  name: 'Autodesk Inc',                    price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'AAPL',  name: 'Apple Inc',                       price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'AMAT',  name: 'Applied Materials',               price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'APP',   name: 'AppLovin Corp',                   price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'AVGO',  name: 'Broadcom Inc',                    price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'CDNS',  name: 'Cadence Design Systems',          price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'CDW',   name: 'CDW Corporation',                 price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'CIEN',  name: 'Ciena Corporation',               price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'CSCO',  name: 'Cisco Systems',                   price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'CTSH',  name: 'Cognizant Technology Solutions',  price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'COHR',  name: 'Coherent Corp',                   price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'GLW',   name: 'Corning Inc',                     price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'CRM',   name: 'Salesforce Inc',                  price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'CRWD',  name: 'CrowdStrike Holdings',            price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'DDOG',  name: 'Datadog Inc',                     price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'DELL',  name: 'Dell Technologies',               price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'EPAM',  name: 'EPAM Systems',                    price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'FFIV',  name: 'F5 Inc',                          price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'FICO',  name: 'Fair Isaac Corporation',          price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'FSLR',  name: 'First Solar Inc',                 price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'FTNT',  name: 'Fortinet Inc',                    price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'GEN',   name: 'Gen Digital Inc',                 price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'GDDY',  name: 'GoDaddy Inc',                     price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'HPE',   name: 'Hewlett Packard Enterprise',      price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'HPQ',   name: 'HP Inc',                          price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'IBM',   name: 'IBM Corp',                        price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'INTC',  name: 'Intel Corp',                      price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'INTU',  name: 'Intuit Inc',                      price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'IT',    name: 'Gartner Inc',                     price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'JBL',   name: 'Jabil Inc',                       price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'KEYS',  name: 'Keysight Technologies',           price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'KLAC',  name: 'KLA Corporation',                 price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'LRCX',  name: 'Lam Research Corp',               price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'LITE',  name: 'Lumentum Holdings',               price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'MCHP',  name: 'Microchip Technology',            price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'MU',    name: 'Micron Technology',               price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'MSFT',  name: 'Microsoft Corp',                  price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'MPWR',  name: 'Monolithic Power Systems',        price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'MSI',   name: 'Motorola Solutions',              price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'NTAP',  name: 'NetApp Inc',                      price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'NOW',   name: 'ServiceNow Inc',                  price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'NVDA',  name: 'NVIDIA Corp',                     price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'NXPI',  name: 'NXP Semiconductors',              price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'ON',    name: 'ON Semiconductor',                price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'ORCL',  name: 'Oracle Corp',                     price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'PANW',  name: 'Palo Alto Networks',              price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'PLTR',  name: 'Palantir Technologies',           price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'PTC',   name: 'PTC Inc',                         price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'QCOM',  name: 'Qualcomm Inc',                    price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'SNDK',  name: 'Sandisk Corp',                    price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'STX',   name: 'Seagate Technology',              price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'SMCI',  name: 'Super Micro Computer',            price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'SWKS',  name: 'Skyworks Solutions',              price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'SNPS',  name: 'Synopsys Inc',                    price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'TRMB',  name: 'Trimble Inc',                     price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'TDY',   name: 'Teledyne Technologies',           price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'TER',   name: 'Teradyne Inc',                    price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'TXN',   name: 'Texas Instruments',               price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'VRSN',  name: 'VeriSign Inc',                    price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'WDC',   name: 'Western Digital Corp',            price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'WDAY',  name: 'Workday Inc',                     price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'ZBRA',  name: 'Zebra Technologies',              price: 0, chg: 0, sector: 'Technology',             vol: '' },
  // Materials
  { ticker: 'APD',   name: 'Air Products & Chemicals',        price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'ALB',   name: 'Albemarle Corporation',           price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'AMCR',  name: 'Amcor PLC',                       price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'BALL',  name: 'Ball Corporation',                price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'CF',    name: 'CF Industries Holdings',          price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'CTVA',  name: 'Corteva Inc',                     price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'CRH',   name: 'CRH PLC',                         price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'DD',    name: 'DuPont de Nemours',               price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'DOW',   name: 'Dow Inc',                         price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'ECL',   name: 'Ecolab Inc',                      price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'FCX',   name: 'Freeport-McMoRan Inc',            price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'IFF',   name: 'International Flavors & Fragrances', price: 0, chg: 0, sector: 'Materials',           vol: '' },
  { ticker: 'IP',    name: 'International Paper Co',          price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'LIN',   name: 'Linde PLC',                       price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'LYB',   name: 'LyondellBasell Industries',       price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'MOS',   name: 'Mosaic Company',                  price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'NEM',   name: 'Newmont Corporation',             price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'NUE',   name: 'Nucor Corporation',               price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'PKG',   name: 'Packaging Corp of America',       price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'PPG',   name: 'PPG Industries',                  price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'SHW',   name: 'Sherwin-Williams Co',             price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'STLD',  name: 'Steel Dynamics Inc',              price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'VMC',   name: 'Vulcan Materials Co',             price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'AVY',   name: 'Avery Dennison Corp',             price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'BG',    name: 'Bunge Global SA',                 price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'SW',    name: 'Smurfit Westrock PLC',            price: 0, chg: 0, sector: 'Materials',              vol: '' },
  // Real Estate
  { ticker: 'ARE',   name: 'Alexandria Real Estate Equities', price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'AMT',   name: 'American Tower Corp',             price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'AVB',   name: 'AvalonBay Communities',           price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'BXP',   name: 'BXP Inc',                         price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'CPT',   name: 'Camden Property Trust',           price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'CBRE',  name: 'CBRE Group Inc',                  price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'CCI',   name: 'Crown Castle Inc',                price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'CSGP',  name: 'CoStar Group Inc',                price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'DLR',   name: 'Digital Realty Trust',            price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'DOC',   name: 'Healthpeak Properties',           price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'EQIX',  name: 'Equinix Inc',                     price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'EQR',   name: 'Equity Residential',              price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'ESS',   name: 'Essex Property Trust',            price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'EXR',   name: 'Extra Space Storage',             price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'FRT',   name: 'Federal Realty Investment Trust', price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'HST',   name: 'Host Hotels & Resorts',           price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'INVH',  name: 'Invitation Homes Inc',            price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'IRM',   name: 'Iron Mountain Inc',               price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'KIM',   name: 'Kimco Realty Corp',               price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'MAA',   name: 'Mid-America Apartment Communities', price: 0, chg: 0, sector: 'Real Estate',          vol: '' },
  { ticker: 'O',     name: 'Realty Income Corp',              price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'REG',   name: 'Regency Centers Corp',            price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'SBAC',  name: 'SBA Communications Corp',         price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'SPG',   name: 'Simon Property Group',            price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'UDR',   name: 'UDR Inc',                         price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'VTR',   name: 'Ventas Inc',                      price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'VICI',  name: 'Vici Properties Inc',             price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'WELL',  name: 'Welltower Inc',                   price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'WY',    name: 'Weyerhaeuser Co',                 price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'PLD',   name: 'Prologis Inc',                    price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'PSA',   name: 'Public Storage',                  price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  // Utilities
  { ticker: 'AES',   name: 'AES Corporation',                 price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'LNT',   name: 'Alliant Energy Corp',             price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'AEE',   name: 'Ameren Corporation',              price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'AEP',   name: 'American Electric Power',         price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'AWK',   name: 'American Water Works',            price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'ATO',   name: 'Atmos Energy Corp',               price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'CEG',   name: 'Constellation Energy',            price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'CNP',   name: 'CenterPoint Energy',              price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'CMS',   name: 'CMS Energy Corp',                 price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'ED',    name: 'Consolidated Edison',             price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'D',     name: 'Dominion Energy Inc',             price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'DTE',   name: 'DTE Energy Co',                   price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'DUK',   name: 'Duke Energy Corp',                price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'EIX',   name: 'Edison International',            price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'ETR',   name: 'Entergy Corporation',             price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'EVRG',  name: 'Evergy Inc',                      price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'ES',    name: 'Eversource Energy',               price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'EXC',   name: 'Exelon Corporation',              price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'FE',    name: 'FirstEnergy Corp',                price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'NEE',   name: 'NextEra Energy Inc',              price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'NI',    name: 'NiSource Inc',                    price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'NRG',   name: 'NRG Energy Inc',                  price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'PCG',   name: 'PG&E Corporation',                price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'PNW',   name: 'Pinnacle West Capital',           price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'PPL',   name: 'PPL Corporation',                 price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'PEG',   name: 'Public Service Enterprise Group', price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'SRE',   name: 'Sempra',                          price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'SO',    name: 'Southern Co',                     price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'VST',   name: 'Vistra Corp',                     price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'WEC',   name: 'WEC Energy Group',                price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'XEL',   name: 'Xcel Energy Inc',                 price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  // ETFs
  { ticker: 'SPY',   name: 'SPDR S&P 500 ETF',                price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'QQQ',   name: 'Invesco QQQ Trust',               price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'IWM',   name: 'iShares Russell 2000 ETF',        price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'DIA',   name: 'SPDR Dow Jones ETF',              price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'GLD',   name: 'SPDR Gold Shares',                price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'XLF',   name: 'Financial Select Sector SPDR',    price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'XLK',   name: 'Technology Select Sector SPDR',   price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'XLE',   name: 'Energy Select Sector SPDR',       price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'ARKK',  name: 'ARK Innovation ETF',              price: 0, chg: 0, sector: 'ETF',                    vol: '' },
];

export function fmt(n: number): string {
  return '$' + n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export function fmtPct(n: number): string {
  return (n >= 0 ? '+' : '') + n.toFixed(2) + '%';
}
