import { Stock } from './types';

export const STOCKS: Stock[] = [
  // Technology
  { ticker: 'AAPL',  name: 'Apple Inc',                   price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'MSFT',  name: 'Microsoft Corp',               price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'NVDA',  name: 'NVIDIA Corp',                  price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'GOOGL', name: 'Alphabet Inc (Class A)',        price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'GOOG',  name: 'Alphabet Inc (Class C)',        price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'META',  name: 'Meta Platforms Inc',            price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'TSLA',  name: 'Tesla Inc',                    price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'AVGO',  name: 'Broadcom Inc',                  price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'ORCL',  name: 'Oracle Corp',                   price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'CRM',   name: 'Salesforce Inc',                price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'AMD',   name: 'Advanced Micro Devices',        price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'INTC',  name: 'Intel Corp',                    price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'QCOM',  name: 'Qualcomm Inc',                  price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'TXN',   name: 'Texas Instruments',             price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'NOW',   name: 'ServiceNow Inc',                price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'SNOW',  name: 'Snowflake Inc',                 price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'PLTR',  name: 'Palantir Technologies',         price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'MU',    name: 'Micron Technology',             price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'AMAT',  name: 'Applied Materials',             price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'ADBE',  name: 'Adobe Inc',                     price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'UBER',  name: 'Uber Technologies',             price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'NET',   name: 'Cloudflare Inc',                price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'SHOP',  name: 'Shopify Inc',                   price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'SQ',    name: 'Block Inc',                     price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'COIN',  name: 'Coinbase Global',               price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'APP',   name: 'AppLovin Corp',                 price: 0, chg: 0, sector: 'Technology',             vol: '' },
  // Consumer
  { ticker: 'AMZN',  name: 'Amazon.com Inc',                price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'HD',    name: 'Home Depot Inc',                price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'MCD',   name: "McDonald's Corp",               price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'NKE',   name: 'Nike Inc',                      price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'SBUX',  name: 'Starbucks Corp',                price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'TGT',   name: 'Target Corp',                   price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'WMT',   name: 'Walmart Inc',                   price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'COST',  name: 'Costco Wholesale',              price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'PG',    name: 'Procter & Gamble',              price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'KO',    name: 'Coca-Cola Co',                  price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  { ticker: 'PEP',   name: 'PepsiCo Inc',                   price: 0, chg: 0, sector: 'Consumer Staples',       vol: '' },
  // Financials
  { ticker: 'JPM',   name: 'JPMorgan Chase & Co',           price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'V',     name: 'Visa Inc',                      price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'MA',    name: 'Mastercard Inc',                price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'BAC',   name: 'Bank of America Corp',          price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'GS',    name: 'Goldman Sachs Group',           price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'MS',    name: 'Morgan Stanley',                price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'BRK-B', name: 'Berkshire Hathaway B',          price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'WFC',   name: 'Wells Fargo & Co',              price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'AXP',   name: 'American Express Co',           price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'BLK',   name: 'BlackRock Inc',                 price: 0, chg: 0, sector: 'Financials',             vol: '' },
  { ticker: 'PYPL',  name: 'PayPal Holdings',               price: 0, chg: 0, sector: 'Financials',             vol: '' },
  // Health Care
  { ticker: 'LLY',   name: 'Eli Lilly and Co',              price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'JNJ',   name: 'Johnson & Johnson',             price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'UNH',   name: 'UnitedHealth Group',            price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'NVO',   name: 'Novo Nordisk A/S',              price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'ABBV',  name: 'AbbVie Inc',                    price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'MRK',   name: 'Merck & Co',                    price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'PFE',   name: 'Pfizer Inc',                    price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'TMO',   name: 'Thermo Fisher Scientific',      price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'ISRG',  name: 'Intuitive Surgical',            price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  // Energy
  { ticker: 'XOM',   name: 'Exxon Mobil Corp',              price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'CVX',   name: 'Chevron Corp',                  price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'COP',   name: 'ConocoPhillips',                price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  // Industrials & Other
  { ticker: 'BA',    name: 'Boeing Co',                     price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'CAT',   name: 'Caterpillar Inc',               price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'GE',    name: 'GE Aerospace',                  price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'RTX',   name: 'RTX Corp',                      price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'UPS',   name: 'United Parcel Service',         price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  // Real Estate
  { ticker: 'AMT',   name: 'American Tower Corp',           price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'PLD',   name: 'Prologis Inc',                  price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'EQIX',  name: 'Equinix Inc',                   price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'SPG',   name: 'Simon Property Group',          price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  { ticker: 'O',     name: 'Realty Income Corp',            price: 0, chg: 0, sector: 'Real Estate',            vol: '' },
  // Utilities
  { ticker: 'NEE',   name: 'NextEra Energy Inc',            price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'DUK',   name: 'Duke Energy Corp',              price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  { ticker: 'SO',    name: 'Southern Co',                   price: 0, chg: 0, sector: 'Utilities',              vol: '' },
  // Materials
  { ticker: 'LIN',   name: 'Linde PLC',                     price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'APD',   name: 'Air Products & Chemicals',      price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'NEM',   name: 'Newmont Corp',                  price: 0, chg: 0, sector: 'Materials',              vol: '' },
  { ticker: 'FCX',   name: 'Freeport-McMoRan Inc',          price: 0, chg: 0, sector: 'Materials',              vol: '' },
  // Communication Services
  { ticker: 'NFLX',  name: 'Netflix Inc',                   price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'DIS',   name: 'Walt Disney Co',                price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'CMCSA', name: 'Comcast Corp',                  price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'T',     name: 'AT&T Inc',                      price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'VZ',    name: 'Verizon Communications',        price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'SNAP',  name: 'Snap Inc',                      price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  { ticker: 'SPOT',  name: 'Spotify Technology',            price: 0, chg: 0, sector: 'Communication Services', vol: '' },
  // More Technology
  { ticker: 'CRWD',  name: 'CrowdStrike Holdings',          price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'PANW',  name: 'Palo Alto Networks',            price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'DDOG',  name: 'Datadog Inc',                   price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'ZS',    name: 'Zscaler Inc',                   price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'HUBS',  name: 'HubSpot Inc',                   price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'TWLO',  name: 'Twilio Inc',                    price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'U',     name: 'Unity Software',                price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'RBLX',  name: 'Roblox Corp',                   price: 0, chg: 0, sector: 'Technology',             vol: '' },
  { ticker: 'HOOD',  name: 'Robinhood Markets',             price: 0, chg: 0, sector: 'Financials',             vol: '' },
  // More Health Care
  { ticker: 'CVS',   name: 'CVS Health Corp',               price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'MDT',   name: 'Medtronic PLC',                 price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'AMGN',  name: 'Amgen Inc',                     price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'GILD',  name: 'Gilead Sciences',               price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  { ticker: 'MRNA',  name: 'Moderna Inc',                   price: 0, chg: 0, sector: 'Health Care',            vol: '' },
  // More Industrials
  { ticker: 'HON',   name: 'Honeywell International',       price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'LMT',   name: 'Lockheed Martin Corp',          price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'DE',    name: 'Deere & Company',               price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  { ticker: 'FDX',   name: 'FedEx Corp',                    price: 0, chg: 0, sector: 'Industrials',            vol: '' },
  // More Energy
  { ticker: 'SLB',   name: 'SLB (Schlumberger)',            price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  { ticker: 'EOG',   name: 'EOG Resources',                 price: 0, chg: 0, sector: 'Energy',                 vol: '' },
  // More Consumer
  { ticker: 'LOW',   name: 'Lowe\'s Companies',             price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'TJX',   name: 'TJX Companies',                 price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'BKNG',  name: 'Booking Holdings',              price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'MAR',   name: 'Marriott International',        price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'F',     name: 'Ford Motor Co',                 price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'GM',    name: 'General Motors Co',             price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'ABNB',  name: 'Airbnb Inc',                    price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  { ticker: 'LYFT',  name: 'Lyft Inc',                      price: 0, chg: 0, sector: 'Consumer Discretionary', vol: '' },
  // ETFs
  { ticker: 'SPY',   name: 'SPDR S&P 500 ETF',              price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'QQQ',   name: 'Invesco QQQ Trust',             price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'IWM',   name: 'iShares Russell 2000 ETF',      price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'DIA',   name: 'SPDR Dow Jones ETF',            price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'GLD',   name: 'SPDR Gold Shares',              price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'XLF',   name: 'Financial Select Sector SPDR',  price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'XLK',   name: 'Technology Select Sector SPDR', price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'XLE',   name: 'Energy Select Sector SPDR',     price: 0, chg: 0, sector: 'ETF',                    vol: '' },
  { ticker: 'ARKK',  name: 'ARK Innovation ETF',            price: 0, chg: 0, sector: 'ETF',                    vol: '' },
];


export function fmt(n: number): string {
  return '$' + n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export function fmtPct(n: number): string {
  return (n >= 0 ? '+' : '') + n.toFixed(2) + '%';
}
